env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - tsconfig.base.json
plugins:
  - "@typescript-eslint"
rules:
  semi:
    - error
    - always
  quotes:
    - error
    - double
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
