extends:
  - ../../.eslintrc.yaml
  - plugin:react-hooks/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:jsx-a11y/recommended
plugins:
  - react
settings:
  react:
    version: detect
rules:
  react/no-array-index-key: error
