FROM node:18.12.0-alpine as base

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc tsconfig.base.json ./
COPY apps/auth/package.json ./apps/auth/package.json
COPY apps/frontend/package.json ./apps/frontend/package.json

RUN pnpm install --unsafe-perm --frozen-lockfile

COPY apps ./apps
COPY packages ./packages

RUN pnpm --filter auth run build

EXPOSE 3000

ENTRYPOINT ["pnpm", "--filter", "auth", "run", "start"]