FROM node:18.12.0-alpine as base

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc tsconfig.base.json ./
COPY apps/marketplace/package.json ./apps/marketplace/package.json
COPY apps/frontend/package.json ./apps/frontend/package.json

RUN pnpm install --unsafe-perm --frozen-lockfile

COPY apps ./apps
COPY packages ./packages

RUN pnpm --filter marketplace run build

EXPOSE 3002

ENTRYPOINT ["pnpm", "--filter", "marketplace", "run", "start"]